#! /bin/sh

wget -q -O ./sbhostsdownload-fakenews https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-only/hosts
echo "server:" > ../conf/sbhosts-fakenews.conf
cat ./sbhostsdownload-fakenews | grep '^0\.0\.0\.0' | awk '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2". A 0.0.0.0\""}' >> ../conf/sbhosts-fakenews.conf
rm ./sbhostsdownload-fakenews