#! /bin/sh

wget -q -O ./sbhostsdownload-gambling https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-only/hosts
echo "server:" > ../conf/sbhosts-gambling.conf
cat ./sbhostsdownload-gambling | grep '^0\.0\.0\.0' | awk '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2". A 0.0.0.0\""}' >> ../conf/sbhosts-gambling.conf
rm ./sbhostsdownload-gambling