#! /bin/sh

wget -q -O ./sbhostsdownload https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
echo "server:" > ../conf/sbhosts.conf
cat ./sbhostsdownload | grep '^0\.0\.0\.0' | awk '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2". A 0.0.0.0\""}' >> ../conf/sbhosts.conf
rm ./sbhostsdownload